# Generated by Django 4.2.5 on 2023-09-21 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('dueDate', models.DateField()),
                ('status', models.BooleanField()),
                ('discipline', models.ManyToManyField(to='studentControl.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentControl.student')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentControl.discipline')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentControl.task')),
            ],
        ),
    ]
